### ISSUE TITLE
 TypeError: undefined is not a function, js engine: hermes

### ISSUE THREAD

**Issue by francesco-clementi-92** [aarongrider/vision-camera-ocr#4]
I installed correctly react-native-reanimated and I have the exact issue of:

[https://github.com/mrousavy/react-native-vision-camera/issues/798](url)

but can't find a way to fix it, even moving around the import of react-native-reanimated.

The full stack is:
```
Error: ENOENT: no such file or directory, open '/Users/francescoclementi/Documents/development/parkingmgmt-native/http:/localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.parkingmgmtnative&modulesOnly=false&runModule=true'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at getCodeFrame (/Users/francescoclementi/Documents/development/parkingmgmt-native/node_modules/metro/src/Server.js:919:18)
    at Server._symbolicate (/Users/francescoclementi/Documents/development/parkingmgmt-native/node_modules/metro/src/Server.js:992:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Server._processRequest (/Users/francescoclementi/Documents/development/parkingmgmt-native/node_modules/metro/src/Server.js:403:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/francescoclementi/Documents/development/parkingmgmt-native/http:/localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.parkingmgmtnative&modulesOnly=false&runModule=true'
}
Error: ENOENT: no such file or directory, open '/Users/francescoclementi/Documents/development/parkingmgmt-native/http:/localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.parkingmgmtnative&modulesOnly=false&runModule=true'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at getCodeFrame (/Users/francescoclementi/Documents/development/parkingmgmt-native/node_modules/metro/src/Server.js:919:18)
    at Server._symbolicate (/Users/francescoclementi/Documents/development/parkingmgmt-native/node_modules/metro/src/Server.js:992:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Server._processRequest (/Users/francescoclementi/Documents/development/parkingmgmt-native/node_modules/metro/src/Server.js:403:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/francescoclementi/Documents/development/parkingmgmt-native/http:/localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.parkingmgmtnative&modulesOnly=false&runModule=true'
}
 ERROR  TypeError: undefined is not a function, js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

**Comment by CodingWithNobody** [comment]
Check this https://www.youtube.com/watch?v=kOYP2Xun_6o&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=77
